import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="overflow-hidden w-screen min-h-screen relative">
				<div className="navbar h-20 w-full" />
				<main>{children}</main>
				<div className="footer" />
			</body>
		</html>
	);
}
